variables:
  TEST_ENV: 'dev'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: npx playwright test tests/firstweek/day2.spec.ts --project=chromium
  displayName: 'Run Selected Test'
  env:
    TEST_ENV: $(TEST_ENV)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/*.xml'
    failTaskOnFailedTests: true
- script: npm install -g allure-commandline --save-dev
  displayName: 'Install Allure CLI'    
- script: npx allure generate allure-results --clean -o allure-report
  displayName: 'Generate Allure Report'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'playwright-report'
    artifactName: 'playwright-report'        